# Generated by Django 4.2.2 on 2023-07-04 17:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Указать логин пользователя', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Логин содержит один или несколько недопустимых символов!', regex='^[\\w.@+-]+\\Z')], verbose_name='Логин пользователя'),
        ),
    ]
