version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13-bullseye
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: 
      context: ./backend/foodgram_backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - web

  gateway:
    build: ./infra/
    restart: always
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static:/var/html/backend_static/
      - media:/var/html/media/
    depends_on:
      - web
      - frontend
