version: '3.3'

volumes:
  pg_data:
  static:
  media:
  html:

services:

  db:
    image: postgres:13-bullseye
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    image: pittchai/foodgram_backend
    env_file: .env
    restart: always
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
      - html:/app/static_file/html/
    depends_on:
      - db

  frontend:
    image: pittchai/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - web

  gateway:
    image: pittchai/foodgram_nginx
    restart: always
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static:/var/html/static/
      - media:/var/html/media/
      - html:/var/html/
    depends_on:
      - web
      - frontend