
AMOUNT_CHAR_TO_SLICE: int = 15
HEADER_FONT_SIZE: int = 20
BODY_FONT_SIZE: int = 15
HEADER_LEFT_MARGIN: int = 100
BODY_LEFT_MARGIN: int = 80
HEADER_HEIGHT: int = 770
BODY_FIRST_LINE_HEIGHT: int = 740
LINE_SPACING: int = 20
BOTTOM_MARGIN: int = 100
BULLET_POINT_SYMBOL = u'\u2023'
